services:
  db:
    container_name: database
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  web:
    container_name: back
    image: backend:v1.2
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db